logging:
  level:
    org:
      springframework: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:bugtracker
  h2:
    console:
      enabled: true
      path: /h2
  thymeleaf:
    template-loader-path: classpath:/templates
    suffix: .html
    cache: false
