spring:
  datasource:
    url: ${DB_URL}
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 5001
app:
  version: 1.1.0